version: '3.4'
#this file is for additional configurations for the images in the docker-compose.yml
services:
  catalogdb:
    container_name: catalogdb
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=CatalogDb
    restart: always
    ports:
    - "5432:5432"
    volumes:
     - postgres_catalog:/var/lib/postgresql/data/